feat: update dispenser address and ABI
valory-xyz/autonolas-tokenomics-frontend pull request #132
Opened 2024-07-25 11:24 UTC by mohandast52

2024-07-25 13:16 UTC, kupermind approved these changes, later dismissed

2024-07-25 13:32 UTC, Tanya-atatakai approved these changes, later dismissed

2024-07-25 13:40 UTC, truemiller submitted a review, later dismissed
pre-emptively approving, just need tokenomics ABI update?

2024-07-25 13:51 UTC, Tanya-atatakai approved these changes

2024-07-25 13:51 UTC, Tanya-atatakai commented on common-util/abiAndAddresses/tokenomics.js
> +  contractName: 'Tokenomics',
doesn't affect anything, but the name has not changed https://etherscan.io/address/0xc096362fa6f4A4B1a9ea68b1043416f3381ce300#code

2024-07-25 13:51 UTC, Tanya-atatakai requested changes
@mohandast52 can you please fix tests

2024-07-26 10:54 UTC, Tanya-atatakai approved these changes

2024-07-28 03:43 UTC, kupermind approved these changes

2024-07-28 15:33 UTC, DavidMinarsch approved these changes

2024-07-28 15:34 UTC, merged